### PR TITLE
4 fix percent function

### LINKED ISSUE #4: kittenFormat.percent(1) return '100%'
Capture d’écran 2022-03-03 à 09 18 42

### PR DESCRIPTION
**Pull request by cdroillard**

### CODE REVIEW

File: lib/number.js [hunk 1]
```diff
@@ -154,8 +154,9 @@ export function averageN (value, options) {
 /**
  * Set a number as a percentage
  * @param {Number} value
+ * @param {Object} { isAlreadyPercentageNumber : {Boolean}  }
  */
-export function percent (value) {
+export function percent (value, option) {
```
Comment (matthieurobin) [inline lib/number.js]: option -> options

File: tests/test.number.js [hunk 2]
```diff
@@ -453,8 +453,25 @@ describe('number', () => {
...
+      should(sanitizeSpaces(kittenFormat.percent(12.56, _options))).eql('12,56%');
+    });
+
+    it('should set percentage of a number = 1 with isAlreadyPercentageNumber', () => {
+      var _options = {
+        isAlreadyPercentageNumber : true
+      };
+      should(sanitizeSpaces(kittenFormat.percent(1, _options))).eql('1%');
+    });
+
```
Comment (matthieurobin) [inline tests/test.number.js:473]: add a test for 1 with isAlreadyPercentageNumber = false, ;)
